# Generated by Django 5.0.4 on 2024-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
    ]
