# Generated by Django 4.2.15 on 2024-09-04 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="serializer_class",
            new_name="description",
        ),
    ]
